### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by 9o0p** [SimpleSandman/UmaMusumeToolbox#1]
![image](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/133234216/416003a3-7b72-4c36-a612-9a5b769a687c)

my os is window 11
I installed dotnet 3.5, 4.7.2, 4.8.0, 5.0, 6.0, 7.0 ... yet still not working. what should I check more?

**Comment by SimpleSandman** [comment]
Do you have both the `.exe` and `.json` in the same folder?

This screenshot is to ensure you have both the `UmaMusumeToolbox.DataDownload.exe` and `appsettings.json` in the same folder.
![image](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/14926100/349f11d8-83fa-45d4-b1c0-b281bada2dab)

For re-validation, I downloaded a fresh copy of this repo's [releases](https://github.com/SimpleSandman/UmaMusumeToolbox/releases) just before posting this comment. Since you didn't post what's inside your `appsettings.json`, I can only assume you didn't adjust the folder locations away from what's already inside.

The contents inside the `appsettings.json`:
```json
{
  "Settings": {
    "IsDebugMode": false,
    "MasterDbFilepath": "C:\\Users\\kento\\AppData\\LocalLow\\Cygames\\umamusume\\master\\master.mdb",
    "MetaDbFilepath": "C:\\Users\\kento\\AppData\\LocalLow\\Cygames\\umamusume\\meta",
    "SkipExistingFiles": true,
    "TimeoutFromMinutes": 5,
    "UserSavedLocation": "C:\\Users\\kento\\uma_storage"
  }
}
```

If necessary, please refer to [this section](https://github.com/SimpleSandman/UmaMusumeToolbox#config-file-explanation) in the README.md for a deeper explanation.

------------

Just in case you need `dotnet --info` validation from my machine, I've posted screenshots below.
Disclaimer: You may not need all of the .NET runtimes as I've been developing for many years and have many different versions on my machine.

![image](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/14926100/2401e7ff-b024-4629-8904-795bb5a766c7)
![image](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/14926100/0c53d344-82c8-4b05-b624-602ea2bce586)
![image](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/14926100/cf935b62-4c84-42c3-8616-90b53664afe2)

**Comment by 9o0p** [comment]
Now I solved my problem. 
    "UserSavedLocation": "C:\\Users\\kento\\uma_storage"
I used only 1 slash that didn't worked. Adjusted to double slash and it works now.
Thanks a lot!

**Comment by Veshurik** [comment]
Sorry for commenting here, I see this line in .json when it doesn't exists in latest .json file - "MasterDbFilepath": "C:\\Users\\kento\\AppData\\LocalLow\\Cygames\\umamusume\\master\\master.mdb", . It is okay to not include it? Or if I included it, it doesn't matter?

**Comment by SimpleSandman** [comment]
> Sorry for commenting here, I see this line in .json when it doesn't exists in latest .json file - "MasterDbFilepath": "C:\\Users\\kento\\AppData\\LocalLow\\Cygames\\umamusume\\master\\master.mdb", . It is okay to not include it? Or if I included it, it doesn't matter?

It is safe to remove "MasterDbFilepath" from your json file as the assets are only scraped from the "MetaDbFilepath". I had "master.mdb" referenced for future work, but as it's been a few years, I figured I'll clean up unused code for better readability.

This is the commit of me replacing the unused variable with the host URL: 
https://github.com/SimpleSandman/UmaMusumeToolbox/commit/55aa96ac18b3de98c9ae1e34b4fd17a76bd254d0
